name: 'Print something'
description: 'Prints a message to the standard output'
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'Hello world'
outputs:
  time: # id of output
    description: 'The time of the message'	
runs:
  using: 'node16'
  main: 'index.js'
  